services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  second-brain-database:
    image: rohanbatra/second-brain-database:latest  # or use build: . if needed
    container_name: second-brain-database
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - JWT_REFRESH_EXPIRY=${JWT_REFRESH_EXPIRY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - MT_API=${MT_API}
      - REDIS_STORAGE_URI=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

