version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  second-brain-database:
    image: rohanbatra/second-brain-database:latest  # or use build: . if needed
    container_name: second-brain-database
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=second_brain_database
      - SECRET_KEY=PLEASECHANGEME
      - JWT_EXPIRY=3600
      - JWT_REFRESH_EXPIRY=3600
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_STORAGE_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis
