version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    networks:
      - proxy
      - default

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - proxy
      - default

  second_brain_database:
    image: rohanbatra/second_brain_database:dev
    container_name: second_brain_database
    volumes:
      - ../../.sbd_config.json:/sbd_user/.config/Second-Brain-Database/.sbd_config.json:ro
    depends_on:
      - mongo
      - redis
    networks:
      - proxy
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

volumes:
  npm_data:
  npm_letsencrypt:
