"""
RAG Core Module

Core functionality and utilities for the RAG system.
"""

from second_brain_database.rag.core.config import (
    DocumentFormat,
    DocumentProcessingConfig,
    EmbeddingModel,
    LLMConfig,
    LLMProvider,
    MonitoringConfig,
    QueryEngineConfig,
    RAGConfig,
    VectorStoreConfig,
    VectorStoreProvider,
)
from second_brain_database.rag.core.exceptions import (
    AnswerGenerationError,
    AuthenticationError,
    ConfigurationError,
    ContextBuildingError,
    DocumentExtractionError,
    DocumentParsingError,
    DocumentProcessingError,
    EmbeddingError,
    LLMConnectionError,
    LLMError,
    LLMGenerationError,
    LLMRateLimitError,
    PermissionError,
    QueryEngineError,
    QueryRerankingError,
    QueryRetrievalError,
    RAGError,
    RateLimitError,
    UnsupportedDocumentFormatError,
    ValidationError,
    VectorStoreConnectionError,
    VectorStoreError,
    VectorStoreIndexError,
    VectorStoreSearchError,
    format_error_response,
    get_http_status_code,
)
from second_brain_database.rag.core.types import (
    BaseRAGModel,
    ChatMessage,
    ChunkList,
    CitationInfo,
    ConfigDict,
    Conversation,
    Document,
    DocumentChunk,
    DocumentInput,
    DocumentList,
    DocumentMetadata,
    DocumentStatus,
    FilterDict,
    HealthCheck,
    MessageList,
    MetadataDict,
    QueryContext,
    QueryInput,
    QueryRequest,
    QueryResponse,
    QueryType,
    ResponseOutput,
    ResponseType,
    ResultList,
    SearchResult,
    StreamingChunk,
    SystemStatus,
)

__all__ = [
    # Config
    "RAGConfig",
    "DocumentProcessingConfig", 
    "VectorStoreConfig",
    "LLMConfig",
    "QueryEngineConfig",
    "MonitoringConfig",
    "VectorStoreProvider",
    "LLMProvider",
    "DocumentFormat",
    "EmbeddingModel",
    
    # Exceptions
    "RAGError",
    "DocumentProcessingError",
    "DocumentParsingError",
    "DocumentExtractionError", 
    "UnsupportedDocumentFormatError",
    "VectorStoreError",
    "VectorStoreConnectionError",
    "VectorStoreIndexError",
    "VectorStoreSearchError",
    "LLMError",
    "LLMConnectionError",
    "LLMGenerationError",
    "LLMRateLimitError",
    "EmbeddingError",
    "QueryEngineError",
    "QueryRetrievalError",
    "QueryRerankingError",
    "ContextBuildingError",
    "AnswerGenerationError",
    "ConfigurationError",
    "ValidationError",
    "AuthenticationError",
    "PermissionError",
    "RateLimitError",
    "get_http_status_code",
    "format_error_response",
    
    # Types
    "DocumentStatus",
    "QueryType",
    "ResponseType",
    "BaseRAGModel",
    "DocumentMetadata",
    "DocumentChunk",
    "Document",
    "QueryContext",
    "SearchResult",
    "QueryRequest",
    "CitationInfo",
    "QueryResponse",
    "StreamingChunk",
    "ChatMessage",
    "Conversation",
    "SystemStatus",
    "HealthCheck",
    "DocumentList",
    "ChunkList", 
    "ResultList",
    "MessageList",
    "DocumentInput",
    "QueryInput",
    "ResponseOutput",
    "ConfigDict",
    "MetadataDict",
    "FilterDict",
]