name: Build and Push Docker Image to GHCR

# Trigger the action when pushing to the main branch
on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (needed for building Docker images in GitHub Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub before building and pushing (good practice)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rohanbatra
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker image (Docker Hub)
        run: |
          docker build -t rohanbatra/second_brain_database:latest .
          docker push rohanbatra/second_brain_database:latest
  
      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rohanbatrain/second_brain_database/dev
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
