name: Build and Push Docker Image to GHCR

# Trigger the action when pushing to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (needed for building Docker images in GitHub Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image (github)
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/second-brain-database:latest .

      - name: Build Docker image (docker hub)
        run: |
          docker build -t rohanbatra/second-brain-database:latest .

      - name: Publish Docker image (docker hub)
        run: |
          docker login -u rohanbatra -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push rohanbatra/second-brain-database:latest

      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rohanbatrain/second_brain_database/core
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
