name: Build and Push Docker Image to GHCR

# Trigger the action when pushing to the main branch
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (needed for building Docker images in GitHub Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub before building and pushing (good practice)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rohanbatra
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker image (Docker Hub)
        run: |
          docker build -t rohanbatra/second-brain-database:dev .
          docker push rohanbatra/second-brain-database:dev

      - name: Publish to Github Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          # The name format for GHCR should be owner/repository_name/image_name.
          # github.repository gives you "owner/repo_name".
          # The 'registry' parameter adds "ghcr.io/" automatically.
          name: ${{ github.repository }}/${{ env.IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          # You can specify tags here. Using 'latest' and a short SHA for traceability.
          # tags: "latest,${{ github.sha }}" # Example for multiple tags
          tags: "dev" # Using 'dev' as per your original request

          # You can also use "buildargs" if your Dockerfile requires them
          # buildargs: "VERSION=1.0"
