name: Build, Push Docker Image & Publish to PyPI

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Only run on version branches like v0.0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rohanbatra
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from branch
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/heads/v}" >> $GITHUB_ENV

      - name: Build and Push Docker image to Docker Hub
        run: |
          docker build -t rohanbatra/second-brain-database:${{ env.VERSION }} .
          docker push rohanbatra/second-brain-database:${{ env.VERSION }}

      - name: Push Docker image to GitHub Container Registry (GHCR)
        run: |
          docker tag rohanbatra/second-brain-database:${{ env.VERSION }} ghcr.io/rohanbatrain/second_brain_database:${{ env.VERSION }}
          docker push ghcr.io/rohanbatrain/second_brain_database:${{ env.VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies for PyPI publishing
        run: |
          pip install setuptools wheel twine

      - name: Build Python package
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
